networks:
  spotify_net:

services:
  server:
    env_file: .env
    environment:
      - GRPC_HOST=grpc
      - SERVER_HOST=0.0.0.0
    build:
      context: .
      args:
        - APP=server
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      - spotify_net
    depends_on:
      - grpc

  grpc:
    env_file: .env
    environment:
      - GRPC_HOST=grpc
    build:
      context: .
      args:
        - APP=grpc
    networks:
      - spotify_net
