// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: protocols/spotify.proto

package protocols

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protocols_spotify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_spotify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protocols_spotify_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Reponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	E             string                 `protobuf:"bytes,2,opt,name=E,proto3" json:"E,omitempty"`
	Track         *Track                 `protobuf:"bytes,3,opt,name=track,proto3,oneof" json:"track,omitempty"`
	Progress      *int64                 `protobuf:"varint,4,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reponse) Reset() {
	*x = Reponse{}
	mi := &file_protocols_spotify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reponse) ProtoMessage() {}

func (x *Reponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_spotify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reponse.ProtoReflect.Descriptor instead.
func (*Reponse) Descriptor() ([]byte, []int) {
	return file_protocols_spotify_proto_rawDescGZIP(), []int{1}
}

func (x *Reponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Reponse) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

func (x *Reponse) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *Reponse) GetProgress() int64 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Album         *Album                 `protobuf:"bytes,1,opt,name=album,proto3" json:"album,omitempty"`
	Artist        []*Artist              `protobuf:"bytes,2,rep,name=artist,proto3" json:"artist,omitempty"`
	ID            string                 `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	IsPlaying     bool                   `protobuf:"varint,5,opt,name=is_playing,json=isPlaying,proto3" json:"is_playing,omitempty"`
	PlayedAt      *int64                 `protobuf:"varint,6,opt,name=played_at,json=playedAt,proto3,oneof" json:"played_at,omitempty"`
	Timestamp     *Timestamp             `protobuf:"bytes,7,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	URL           string                 `protobuf:"bytes,9,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_protocols_spotify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_spotify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_protocols_spotify_proto_rawDescGZIP(), []int{2}
}

func (x *Track) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

func (x *Track) GetArtist() []*Artist {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *Track) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Track) GetIsPlaying() bool {
	if x != nil {
		return x.IsPlaying
	}
	return false
}

func (x *Track) GetPlayedAt() int64 {
	if x != nil && x.PlayedAt != nil {
		return *x.PlayedAt
	}
	return 0
}

func (x *Track) GetTimestamp() *Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Progress      int64                  `protobuf:"varint,1,opt,name=progress,proto3" json:"progress,omitempty"`
	Duration      int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_protocols_spotify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_spotify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_protocols_spotify_proto_rawDescGZIP(), []int{3}
}

func (x *Timestamp) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Timestamp) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	URL           string                 `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_protocols_spotify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_spotify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_protocols_spotify_proto_rawDescGZIP(), []int{4}
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artist) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageURL      string                 `protobuf:"bytes,1,opt,name=imageURL,proto3" json:"imageURL,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ID            string                 `protobuf:"bytes,3,opt,name=ID,proto3" json:"ID,omitempty"`
	URL           string                 `protobuf:"bytes,4,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_protocols_spotify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_spotify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_protocols_spotify_proto_rawDescGZIP(), []int{5}
}

func (x *Album) GetImageURL() string {
	if x != nil {
		return x.ImageURL
	}
	return ""
}

func (x *Album) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Album) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Album) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_protocols_spotify_proto protoreflect.FileDescriptor

const file_protocols_spotify_proto_rawDesc = "" +
	"\n" +
	"\x17protocols/spotify.proto\x12\tprotocols\"\x19\n" +
	"\aRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\x8c\x01\n" +
	"\aReponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\f\n" +
	"\x01E\x18\x02 \x01(\tR\x01E\x12+\n" +
	"\x05track\x18\x03 \x01(\v2\x10.protocols.TrackH\x00R\x05track\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x04 \x01(\x03H\x01R\bprogress\x88\x01\x01B\b\n" +
	"\x06_trackB\v\n" +
	"\t_progress\"\xa8\x02\n" +
	"\x05Track\x12&\n" +
	"\x05album\x18\x01 \x01(\v2\x10.protocols.AlbumR\x05album\x12)\n" +
	"\x06artist\x18\x02 \x03(\v2\x11.protocols.ArtistR\x06artist\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\tR\x02ID\x12\x1d\n" +
	"\n" +
	"is_playing\x18\x05 \x01(\bR\tisPlaying\x12 \n" +
	"\tplayed_at\x18\x06 \x01(\x03H\x00R\bplayedAt\x88\x01\x01\x127\n" +
	"\ttimestamp\x18\a \x01(\v2\x14.protocols.TimestampH\x01R\ttimestamp\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x10\n" +
	"\x03URL\x18\t \x01(\tR\x03URLB\f\n" +
	"\n" +
	"_played_atB\f\n" +
	"\n" +
	"_timestamp\"C\n" +
	"\tTimestamp\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\x03R\bprogress\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\".\n" +
	"\x06Artist\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03URL\x18\x02 \x01(\tR\x03URL\"Y\n" +
	"\x05Album\x12\x1a\n" +
	"\bimageURL\x18\x01 \x01(\tR\bimageURL\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ID\x18\x03 \x01(\tR\x02ID\x12\x10\n" +
	"\x03URL\x18\x04 \x01(\tR\x03URL2q\n" +
	"\aSpotify\x120\n" +
	"\bGetTrack\x12\x12.protocols.Request\x1a\x10.protocols.Track\x124\n" +
	"\bOnListen\x12\x12.protocols.Request\x1a\x12.protocols.Reponse0\x01B\x13Z\x11spotify/protocolsb\x06proto3"

var (
	file_protocols_spotify_proto_rawDescOnce sync.Once
	file_protocols_spotify_proto_rawDescData []byte
)

func file_protocols_spotify_proto_rawDescGZIP() []byte {
	file_protocols_spotify_proto_rawDescOnce.Do(func() {
		file_protocols_spotify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocols_spotify_proto_rawDesc), len(file_protocols_spotify_proto_rawDesc)))
	})
	return file_protocols_spotify_proto_rawDescData
}

var file_protocols_spotify_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protocols_spotify_proto_goTypes = []any{
	(*Request)(nil),   // 0: protocols.Request
	(*Reponse)(nil),   // 1: protocols.Reponse
	(*Track)(nil),     // 2: protocols.Track
	(*Timestamp)(nil), // 3: protocols.Timestamp
	(*Artist)(nil),    // 4: protocols.Artist
	(*Album)(nil),     // 5: protocols.Album
}
var file_protocols_spotify_proto_depIdxs = []int32{
	2, // 0: protocols.Reponse.track:type_name -> protocols.Track
	5, // 1: protocols.Track.album:type_name -> protocols.Album
	4, // 2: protocols.Track.artist:type_name -> protocols.Artist
	3, // 3: protocols.Track.timestamp:type_name -> protocols.Timestamp
	0, // 4: protocols.Spotify.GetTrack:input_type -> protocols.Request
	0, // 5: protocols.Spotify.OnListen:input_type -> protocols.Request
	2, // 6: protocols.Spotify.GetTrack:output_type -> protocols.Track
	1, // 7: protocols.Spotify.OnListen:output_type -> protocols.Reponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protocols_spotify_proto_init() }
func file_protocols_spotify_proto_init() {
	if File_protocols_spotify_proto != nil {
		return
	}
	file_protocols_spotify_proto_msgTypes[1].OneofWrappers = []any{}
	file_protocols_spotify_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocols_spotify_proto_rawDesc), len(file_protocols_spotify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocols_spotify_proto_goTypes,
		DependencyIndexes: file_protocols_spotify_proto_depIdxs,
		MessageInfos:      file_protocols_spotify_proto_msgTypes,
	}.Build()
	File_protocols_spotify_proto = out.File
	file_protocols_spotify_proto_goTypes = nil
	file_protocols_spotify_proto_depIdxs = nil
}
