[server]
host = "localhost"
port = "5050"
prefork = false
timeZone = "#{SPOTIFY_SERVER_TIMEZONE}"

[grpc]
host = "localhost"
port = "4040"

[socket]
origins = ["*"]
readBufferSize = 2048
writeBufferSize = 2048

[spotify]
clientID = "#{SPOTIFY_CLIENT_ID}"
clientSecret = "#{SPOTIFY_CLIENT_SECRET}"
refreshToken = "#{SPOTIFY_REFRESH_TOKEN}"
